#!/usr/bin/env python3
# this_file: src/split_python4gpt/minifier.py
"""Core minification and type-inference logic for split-python4gpt."""

from __future__ import annotations

import contextlib
import logging
import shutil
import subprocess
from ast import ClassDef, FunctionDef, NodeTransformer, fix_missing_locations, parse
from os import environ
from pathlib import Path

from ast import unparse as ast_unparse

from python_minifier import minify

OPENAI_MODELS: dict[str, int] = {
    "gpt-4": 8192,
    "gpt-4-32k": 32768,
    "gpt-4-32k-0613": 32768,
    "gpt-4-0613": 8192,
    "gpt-3.5-turbo": 4096,
    "gpt-3.5-turbo-0613": 4096,
    "gpt-3.5-turbo-16k": 16384,
    "gpt-3.5-turbo-16k-0613": 16384,
}

logger = logging.getLogger(__name__)


class PyTypingMinifier:
    """Minifies Python files and optionally infers types using pytype.

    Attributes:
        PY_TYPE_PY_VER: Python version string used for pytype (e.g. ``"3.10"``).
        PY_TYPE_PY_EXE: Path to the Python executable for that version, or
            ``None`` if not found.
        py_folder: Resolved source folder (set by :meth:`init_folders`).
        out_py_folder: Resolved output folder.
        pyi_folder: Folder used to store ``.pyi`` stubs generated by pytype.
        code_folder_data: Mapping from output path to per-file metadata dict.
    """

    def __init__(self, py_ver: str = "3.10") -> None:
        self.PY_TYPE_PY_VER = py_ver
        self.PY_TYPE_PY_EXE: str | None = shutil.which(f"python{self.PY_TYPE_PY_VER}")
        if not self.PY_TYPE_PY_EXE:
            logger.warning(
                "Python executable for version %s not found. "
                "Type inference with Pytype will likely fail.",
                self.PY_TYPE_PY_VER,
            )
        self.py_folder: Path | None = None
        self.out_py_folder: Path | None = None
        self.pyi_folder: Path | None = None
        self.code_folder_data: dict[Path, dict] = {}

    # ------------------------------------------------------------------
    # Folder / file initialisation helpers
    # ------------------------------------------------------------------

    def init_folders(
        self,
        py_folder: str | Path,
        out_py_folder: str | Path | None = None,
        pyi_folder: str | Path | None = None,
    ) -> None:
        """Resolve and create output folders.

        Args:
            py_folder: Source Python folder.
            out_py_folder: Destination folder for processed files.  Defaults
                to *py_folder* when ``None``.
            pyi_folder: Destination for ``.pyi`` stubs.  Defaults to
                *out_py_folder* when ``None``.
        """
        self.py_folder = Path(py_folder).resolve()
        self.out_py_folder = (
            Path(out_py_folder).resolve() if out_py_folder else self.py_folder
        )
        self.out_py_folder.mkdir(parents=True, exist_ok=True)
        self.pyi_folder = Path(pyi_folder) if pyi_folder else self.out_py_folder
        self.pyi_folder.mkdir(parents=True, exist_ok=True)

    def read_py_file(
        self,
        py_path: str | Path,
        out_py_folder: str | Path | None = None,
        pyi_folder: str | Path | None = None,
    ) -> None:
        """Register a single Python file for processing.

        Args:
            py_path: Path to the source ``.py`` file.
            out_py_folder: Output folder override.
            pyi_folder: Stub folder override.
        """
        py_path = Path(py_path).resolve()
        self.init_folders(py_path.parent, out_py_folder, pyi_folder)
        out_py_path, code_data = self.init_code_data(py_path)
        self.code_folder_data[out_py_path] = code_data

    def read_py_folder(
        self,
        py_folder: str | Path,
        out_py_folder: str | Path | None = None,
        pyi_folder: str | Path | None = None,
    ) -> None:
        """Register all ``.py`` files under *py_folder* for processing.

        Args:
            py_folder: Root of the source tree to process recursively.
            out_py_folder: Output folder override.
            pyi_folder: Stub folder override.
        """
        self.init_folders(py_folder, out_py_folder, pyi_folder)
        for py_path in Path(self.py_folder).rglob("*.py"):  # type: ignore[arg-type]
            out_py_path, code_data = self.init_code_data(py_path)
            self.code_folder_data[out_py_path] = code_data

    def init_code_data(self, py_path: str | Path) -> tuple[Path, dict]:
        """Copy *py_path* to the output folder and build its metadata dict.

        Args:
            py_path: Absolute path to a source ``.py`` file.

        Returns:
            A ``(out_py_path, code_data)`` tuple where *out_py_path* is the
            destination path and *code_data* holds path/content metadata.
        """
        py_path = Path(py_path).resolve()
        rel_py_path = py_path.relative_to(self.py_folder)  # type: ignore[arg-type]
        out_py_path = Path(self.out_py_folder, rel_py_path)  # type: ignore[arg-type]
        rel_out_py_path = out_py_path.relative_to(self.out_py_folder)  # type: ignore[arg-type]
        out_py_path.parent.mkdir(parents=True, exist_ok=True)
        if out_py_path != py_path:
            shutil.copy2(py_path, out_py_path)
        pyi_path = Path(
            self.pyi_folder,  # type: ignore[arg-type]
            ".pytype",
            "pyi",
            rel_out_py_path.with_suffix(".pyi").name,
        )
        py_code = out_py_path.read_text(encoding="utf-8")
        code_data: dict = {
            "py_path": py_path,
            "rel_path": rel_py_path,
            "pyi_path": pyi_path,
            "py_code": py_code,
        }
        return out_py_path, code_data

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def infer_types(self, py_path: Path, pyi_path: Path, py_code: str) -> str:
        """Run pytype on *py_path* and merge type stubs back into the source.

        If the pytype executable is unavailable or fails, a warning is logged
        and the original *py_code* is returned unchanged.

        Args:
            py_path: Absolute path to the (output) Python file to analyse.
            pyi_path: Expected location of the ``.pyi`` stub generated by
                pytype.
            py_code: Current source text of the file.

        Returns:
            Source text annotated with inferred types, or *py_code* unchanged
            on failure.
        """
        if not self.PY_TYPE_PY_EXE:
            logger.warning(
                "Pytype failed for %s: Python %s executable not found.",
                py_path,
                self.PY_TYPE_PY_VER,
            )
            return py_code
        try:
            from pytype.tools.merge_pyi import merge_pyi  # lazy optional import

            command = [
                self.PY_TYPE_PY_EXE,
                "-m",
                "pytype",
                f"--python-version={self.PY_TYPE_PY_VER}",
                str(py_path.relative_to(self.pyi_folder)),  # type: ignore[arg-type]
            ]
            subprocess.run(command, cwd=self.pyi_folder, check=True, capture_output=True)
            pyi_code = pyi_path.read_text(encoding="utf-8")
            py_code = merge_pyi.merge_sources(py=py_code, pyi=pyi_code)
        except Exception as exc:
            logger.warning("Pytype failed for %s: %s", py_path, exc)
        return py_code

    def minify(self, py_code: str, **custom_minify_options: object) -> str:
        """Minify *py_code* using python-minifier with sensible defaults.

        Keyword overrides are merged on top of the defaults, so any
        ``python_minifier.minify`` option can be passed as a keyword argument.

        Args:
            py_code: Python source text to minify.
            **custom_minify_options: Overrides for python-minifier options.

        Returns:
            Minified Python source text.
        """
        minify_options: dict[str, object] = {
            "combine_imports": True,
            "convert_posargs_to_args": True,
            "hoist_literals": False,
            "preserve_shebang": False,
            "remove_annotations": False,
            "remove_asserts": True,
            "remove_debug": True,
            "remove_explicit_return_none": True,
            "remove_literal_statements": True,
            "remove_object_base": True,
            "remove_pass": True,
            "rename_globals": False,
            "rename_locals": False,
        } | custom_minify_options
        return minify(py_code, **minify_options)  # type: ignore[arg-type]

    def process_py(
        self,
        py_path_or_folder: str | Path,
        out_py_folder: str | Path | None = None,
        pyi_folder: str | Path | None = None,
        types: bool = True,
        mini: bool = True,
        **minify_options: object,
    ) -> list[Path]:
        """Process one Python file or an entire directory tree.

        Reads all relevant ``.py`` files, optionally runs type inference and/or
        minification on each one, and writes results to *out_py_folder*.

        Args:
            py_path_or_folder: Path to a single ``.py`` file or a directory.
            out_py_folder: Destination folder for output files.
            pyi_folder: Folder for pytype stub files.
            types: Whether to run pytype type inference.
            mini: Whether to minify the output.
            **minify_options: Extra options forwarded to :meth:`minify`.

        Returns:
            List of absolute paths to all written output files.
        """
        py_path_or_folder = Path(py_path_or_folder).resolve()
        if py_path_or_folder.is_dir():
            self.read_py_folder(py_path_or_folder, out_py_folder, pyi_folder)
        elif py_path_or_folder.is_file():
            self.read_py_file(py_path_or_folder, out_py_folder, pyi_folder)
        else:
            return []

        for out_py_path, code_data in self.code_folder_data.items():
            original_py_code: str = code_data["py_code"]
            py_code: str = original_py_code

            if types:
                py_code = self.infer_types(out_py_path, code_data["pyi_path"], py_code)

            if mini:
                try:
                    py_code = self.minify(py_code, **minify_options)
                except Exception as exc:
                    logger.error("Minification failed for %s: %s", out_py_path, exc)
                    py_code = original_py_code  # fall back to pre-minification text

            code_data["py_code"] = py_code
            out_py_path.write_text(py_code, encoding="utf-8")

        return list(self.code_folder_data.keys())


# ---------------------------------------------------------------------------
# Optional LLM-powered classes (require tiktoken, simpleaichat, astor extras)
# ---------------------------------------------------------------------------


class PyBodySummarizer(NodeTransformer):
    """AST transformer that replaces large function/class bodies with stubs.

    When a function or class body exceeds the token threshold it is replaced
    with ``...`` and (optionally) an AI-generated docstring summary.

    Args:
        py_llm_splitter: The :class:`PyLLMSplitter` instance that drives
            summarisation and token counting.
    """

    def __init__(self, py_llm_splitter: PyLLMSplitter) -> None:
        self.py_llm_splitter = py_llm_splitter

    def visit_FunctionDef(self, node: FunctionDef, code: str | None = None) -> FunctionDef:  # type: ignore[override]
        """Replace *node*'s body with ``...`` (and an AI summary if *code* given).

        Args:
            node: The function AST node to transform.
            code: Minified source of the function body, used to generate a
                summary.  Pass ``None`` to skip summarisation.

        Returns:
            The mutated function node.
        """
        node.body = []
        if code:
            with contextlib.suppress(Exception):
                doc = self.py_llm_splitter.llm_summarize(
                    self.py_llm_splitter.minify(code, remove_literal_statements=False)
                )
                node.body.append(parse(f'"""{doc}"""').body[0])
        node.body.append(parse("...").body[0])
        return node

    def visit_ClassDef(self, node: ClassDef) -> ClassDef:  # type: ignore[override]
        """Summarise oversized methods inside *node*.

        Args:
            node: The class AST node to transform.

        Returns:
            The mutated class node.
        """
        for i, body_node in enumerate(node.body):
            if isinstance(body_node, FunctionDef):
                code = ast_unparse(body_node)
                minified_code = self.py_llm_splitter.minify(
                    code, remove_literal_statements=False
                )
                size = self.py_llm_splitter.gptok_size(minified_code)
                if size > self.py_llm_splitter.gptok_threshold:
                    node.body[i] = self.visit_FunctionDef(body_node, minified_code)
        return node


class PyLLMSplitter(PyTypingMinifier):
    """Extends :class:`PyTypingMinifier` with token-based splitting and LLM summaries.

    Requires the ``llm`` extras: ``tiktoken``, ``simpleaichat``, ``astor``.

    Args:
        *args: Forwarded to :class:`PyTypingMinifier`.
        gptok_model: OpenAI model name used for token counting and
            summarisation.
        gptok_limit: Maximum tokens per output split file.  Defaults to the
            context window of *gptok_model*.
        gptok_threshold: Minimum token count before a function/class body is
            replaced with a stub.
        **kwargs: Forwarded to :class:`PyTypingMinifier`.
    """

    def __init__(
        self,
        *args: object,
        gptok_model: str = "gpt-3.5-turbo",
        gptok_limit: int | None = None,
        gptok_threshold: int = 128,
        **kwargs: object,
    ) -> None:
        super().__init__(*args, **kwargs)  # type: ignore[arg-type]
        self.gptok_model = gptok_model
        self.gptok_limit: int = gptok_limit or OPENAI_MODELS.get(gptok_model, 2048)
        self.gptok_threshold = gptok_threshold
        self.code_summary: dict[str, dict] = {}

        # tiktoken — lazy; fall back to char-count estimate if unavailable
        self.gptoker = None
        try:
            import tiktoken  # lazy optional import

            self.gptoker = tiktoken.encoding_for_model(gptok_model)
        except Exception as exc:
            logger.warning("tiktoken unavailable (%s); using character estimate.", exc)

        # simpleaichat — lazy; LLM summarisation disabled when unavailable
        self.llm_summarize = None
        try:
            from simpleaichat import AIChat  # lazy optional import

            self.llm_summarize = AIChat(
                api_key=environ.get("OPENAI_API_KEY"),
                system=(
                    "Write an extremely short, compact description of this Python code, "
                    'starting with "This class" or "This method" or "This function"'
                ),
                model=self.gptok_model,
            )
        except Exception as exc:
            logger.warning(
                "AIChat unavailable (%s); LLM summarisation disabled.", exc
            )

    def gptok_size(self, text: str) -> int:
        """Count GPT tokens in *text* using the model's tokeniser.

        Falls back to ``len(text) // 4`` (a rough GPT token estimate) when the
        tiktoken encoder is unavailable.

        Args:
            text: Arbitrary text to measure.

        Returns:
            Number of tokens (exact when tiktoken available, estimated otherwise).
        """
        if self.gptoker is not None:
            return len(list(self.gptoker.encode(text)))
        return len(text) // 4  # rough estimate: ~4 chars per token

    def process_py_code(self, py_code: str) -> list[dict]:
        """Split *py_code* into token-bounded sections.

        Large top-level functions and classes are replaced with stubs before
        sectioning.  Uses :func:`ast.unparse` (stdlib) to convert AST nodes
        back to source — no third-party code-generation library required.

        Args:
            py_code: Python source text (already minified/typed).

        Returns:
            List of ``{"py": str, "gptok_size": int}`` dicts.
        """
        tree = parse(py_code)
        sections: list[dict] = []
        body_summary = PyBodySummarizer(self)

        for node in tree.body:
            code = ast_unparse(node)
            minified_code = self.minify(code, remove_literal_statements=False)
            size = self.gptok_size(minified_code)

            if size > self.gptok_threshold and isinstance(node, (FunctionDef, ClassDef)):
                node = body_summary.visit(node)
                fix_missing_locations(node)
                minified_code = self.minify(
                    ast_unparse(node), remove_literal_statements=False
                )
                size = self.gptok_size(minified_code)

            sections.append({"py": minified_code, "gptok_size": size})

        return sections

    def process_py(self, *args: object, **kwargs: object) -> list[Path]:
        """Process files and compute per-file sections for splitting.

        Delegates to :meth:`PyTypingMinifier.process_py` then attaches
        section data to each file entry in :attr:`code_summary`.

        Returns:
            List of output file paths (same as parent return value).
        """
        paths = super().process_py(*args, **kwargs)  # type: ignore[arg-type]

        for path in paths:
            code_data = self.code_folder_data[path]
            sections = self.process_py_code(code_data["py_code"])
            code_data["sections"] = sections
            code_data["gptok_size"] = sum(sec["gptok_size"] for sec in sections)
            self.code_summary[str(path)] = code_data

        return paths

    def write_splits(self) -> None:
        """Write token-bounded split files to ``<out_py_folder>/split4gpt/``.

        Each split file contains consecutive sections from :attr:`code_summary`
        that together do not exceed :attr:`gptok_limit` tokens.  Does nothing
        when :attr:`out_py_folder` has not been set (i.e. no files were
        processed).
        """
        if self.out_py_folder is None:
            logger.warning("write_splits called before process_py; no output folder set.")
            return
        splits_folder = self.out_py_folder / "split4gpt"
        splits_folder.mkdir(parents=True, exist_ok=True)

        textportions: list[str] = []
        current_size = 0
        current_portion: list[str] = []

        for path, code_data in self.code_summary.items():
            header = f"# File: {path}\n"
            current_portion.append(header)
            current_size += self.gptok_size(header)

            for section in code_data["sections"]:
                if current_size + section["gptok_size"] > self.gptok_limit:
                    textportions.append("".join(current_portion))
                    current_portion = []
                    current_size = 0
                current_portion.append(section["py"])
                current_size += section["gptok_size"]

        if current_portion:
            textportions.append("".join(current_portion))

        for i, textportion in enumerate(textportions, start=1):
            (splits_folder / f"split{i}.py").write_text(textportion, encoding="utf-8")
